POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "NullHakim",
  "name" : "Faridlan Nullhakim",
  "password" : "rahasia"
}

### Login

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "NullHakim",
  "password" : "rahasia"
}

### Get User
GET http://localhost:3000/api/users/current
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54

### Logout User
DELETE http://localhost:3000/api/users/current
Accept: application/json
Authorization: f4c09eac-4215-485c-864d-a0321580b903

### Update User
PATCH http://localhost:3000/api/users/current
Accept: application/json
Content-Type: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54

{
  "password" : "rahasia12345"
}

### Create contact
POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54

{
  "first_name" : "Joko",
  "last_name" : "Morro",
  "email" : "joko@example.com",
  "phone" : "089999999"
}

### Update contact
PUT http://localhost:3000/api/contacts/91
Content-Type: application/json
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54

{
  "first_name" : "Budi",
  "last_name" : "Morro",
  "email" : "budi@example.com",
  "phone" : "089999999"
}


### Get contact
GET http://localhost:3000/api/contacts/242
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54

### Delete contact
DELETE http://localhost:3000/api/contacts/241
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54


### Search contact
GET http://localhost:3000/api/contacts
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54


### Create Address
POST http://localhost:3000/api/contacts/242/addresses
Content-Type: application/json
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54

{
  "street" : "jalan contoh",
  "city" : "kota contoh",
  "province" : "provinsi contoh",
  "country" : "negara contoh",
  "postal_code" : "23434"
}

### Get Address
GET http://localhost:3000/api/contacts/242/addresses/113
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54

### List Address
GET http://localhost:3000/api/contacts/242/addresses
Accept: application/json
Authorization: 5a917cc1-bc3d-43a8-a531-1d668dbe7e54

### Update Address
PUT http://localhost:3000/api/contacts/91/addresses/23
Content-Type: application/json
Accept: application/json
Authorization: 051e0dd1-7ef4-43c0-866d-f3c0b2f212f6

{
  "street" : "jalan contoh updated",
  "city" : "kota contoh updated",
  "province" : "provinsi contoh",
  "country" : "negara contoh",
  "postal_code" : "23434"
}

### Remove Address
DELETE http://localhost:3000/api/contacts/91/addresses/23
Accept: application/json
Authorization: 051e0dd1-7ef4-43c0-866d-f3c0b2f212f6


### Login Admin
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "admin",
  "password" : "admin"
}

### Create Seeder
POST http://localhost:3000/api/seeder/run
Content-Type: application/json
Accept: application/json
Authorization: 066cddd6-95e8-41fc-8155-e06c22c25a95

### Clear Seeder
DELETE http://localhost:3000/api/seeder/clear
Content-Type: application/json
Accept: application/json
Authorization: ef128032-a000-4c49-a805-0d13f79f61fc